### ISSUE TITLE
Feature: There is no On/Off button in the player

### ISSUE THREAD

**Issue by FLab-Projects** [hass-agent/HASS.Agent-Integration#8]
Hello! It's clear that you've done a lot of work different from the original Hass Agent integration. Thank you. I use the integration with pleasure and even my girlfriend asked me to configure her computer to work with HASS.

For me at the moment there is only one drawback in integration, or rather two

Since I'm using HomeKit, I'd like to see the computer there, for example, as device_class: tv. For now it looks like a set of switches. I know how to fix this, but it's pointless because the player doesn't have a power button. For me this is the main and most frequently used part. I would like to be able to select a script during setup that will be called by a button (for example, in my case, WakeOnLan). You can also assign an action to shutdown (in my case, hibernation).

The integration itself is great and I love it with all my heart, but I would really like to integrate it into HomeKit as a player with one On/Off button (the most frequently used), and leave the rest of the functionality in Home Assistant.

If you can tell me how to do this myself, I will be very grateful :)

**Comment by amadeo-alex** [comment]
Hello, sorry for the delay in answer :D
So, you'd like the integration to support on/off actions that are user customisable correct?

**Comment by gorbunovav** [comment]
@f1x6r Hi!
As a workaround you can achieve it with the [`Universal Media Player`](https://www.home-assistant.io/integrations/universal/) integration.
It is possible to specify the player provided by HASS Agent as a child for the Universal one and just override missing parts, e.g. power button or sources list:

```yaml
- platform: universal
  unique_id: <some id>
  device_class: tv
  name: desktop
  children:
    - media_player.hass_agent_desktop
  commands:
    turn_on:
      action: button.press
      target:
        entity_id: button.wake_desktop
    turn_off:
      action: button.press
      target:
        entity_id: button.hass_agent_desktop_sleep

    select_source:
      service: mqtt.publish
      data:
        topic: "homeassistant/button/DESKTOP/setaudiooutputcommand/action"
        payload: "{{ source }}"

  attributes:
    source: sensor.desktop_audio_default_device
    source_list: sensor.desktop_audio_output_devices|OutputDevices
```

(you need to expose some additional sensors/commands from HASS Agent for this to work)
